// GET USER BOOKINGS
export const GET_USER_BOOKINGS_REQUEST = 'GET_USER_BOOKINGS_REQUEST';
export const GET_USER_BOOKINGS_SUCCESS = 'GET_USER_BOOKINGS_SUCCESS';
export const GET_USER_BOOKINGS_FAILURE = 'GET_USER_BOOKINGS_FAILURE';

// CREATE BOOKING
export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

// UPDATE BOOKING
export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

// CANCEL BOOKING
export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'CANCEL_BOOKING_FAILURE';

// SET CURRENT BOOKING (for editing)
export const SET_CURRENT_BOOKING = 'SET_CURRENT_BOOKING';